# The base hadoop image to use for all components.
postgresql:
  global:
    postgresql:
      auth:
        username: hive
        password: hive
        database: metastore

  # For easy deployment don't use persistent volumes. Obviously, not proper
  # for production release
  primary:
    persistence:
      enabled: false

    # The apache hive docker image has an jdbc driver that doesn't use the latest encruption
    # settings. Tell postgres to allow access any way
    extendedConfiguration: |-
      password_encryption=md5



# Settings for the hive metastore stateful set
image:
  repository: sslhep/hive-metastore
  tag: 3.1.3
  pullPolicy: IfNotPresent

objectStore:
  externalURI: 
  accessKey:
  secretKey: 

resources: {}
conf:
  hiveSite:
    hive_metastore_uris: thrift://hive-metastore:9083
    # if not set, default hive.metastore.warehouse.dir is default to: "hdfs://{{.Release.Name}}-hdfs:8020/user/hive/warehouse"
    # hive.metastore.warehouse.dir:

aws:
  access_key_id:
  secret_access_key:
  endpoint_url:
